### ISSUE TITLE
Rotation on image does not get applied on export

### ISSUE THREAD

**Issue by dariusstephen** [scenify/design-editor#139]
Thank you for the great repo.
I noticed the image rotation does not get applied on the exported image, unlike the text which is working correctly.

This is tested using mobile Chrome browser, going to https://editor.scenify.dev/

On editor:
![IMG_20220119_182012](https://user-images.githubusercontent.com/4991360/150120329-a0ae0aef-ca5a-47cc-954e-4c6c899a9967.jpg)

Exported image:
![drawing (4)](https://user-images.githubusercontent.com/4991360/150120349-b3255dd7-f8eb-44ab-8ec3-7ab88f35f2ff.png)

Any idea or pointers on how to fix this issue?
Thank you

**Comment by dariusstephen** [comment]
Hi @xorb , thank you so much for the pointers.

I am not quite familiar with how to push the fix to the sdk and npm however the angle seems to work on development mode after updating the file `node_modules/@scenify/sdk/dist/sdk.cjs.development.js`

line 4794: 
from `angle = metadata.angle;`
to `angle = item.angle`

If there is a way for me to apply this fix to the production, I'd love to help.
Thank you

**Comment by xorb** [comment]
Just fixed it. Try scenify-sdk 0.3.3.
Also  this editor is now using 0.3.3
